baseURL = "https://c-tan.com"
languageCode = "en"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
title = "Website of Cheng Tan"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
disqusShortname = "ctan"

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true
