baseURL = "https://c-tan.com"
languageCode = "en"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
title = "Website of Cheng Tan"
theme = ["github.com/adityatelange/hugo-PaperMod"]
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Google Analytics
#googleAnalytics = "UA-123-45"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = true

    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        noClasses = false # 恢复为 PaperMod 推荐的 class 模式
        style = "monokai"