[en]
    languageName = "English"
    weight = 1
    title = "double space"
    [en.params]
        profileMode.enabled = true
        profileMode.title = "Cheng Tan (谭丞)"
        profileMode.subtitle = "orchestrating biomolecules in silico, drifting in life via adagio."
        description = "Website of Cheng Tan"

[zh]
    languageName = "简体中文"
    weight = 2
    title = "句末双空格"
    [zh.params]
        profileMode.enabled = true
        profileMode.title = "谭丞 (Cheng Tan)"
        profileMode.subtitle = "硅基芯片上指挥分子运动，碳基生活中演绎随性变奏。"
        description = "谭丞的个人网站"