[[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

[[main]]
  name = "Blog"
  weight = 200
  identifier = "posts"
  url = "/post/"

[[main]]
  name = "Archive"
  weight = 250
  identifier = "archives"
  url = "/archives/"

[[main]]
  name = "Categories"
  weight = 270
  identifier = "categories"
  url = "/categories/"

[[main]]
  name = "Publications"
  weight = 300
  identifier = "publication"
  url = "/publication/"

[[main]]
  name = "Presentations"
  weight = 400
  identifier = "presentation"
  url = "/presentation/"

[[main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"

[[main]]
  name = "Search"
  weight = 600
  identifier = "search"
  url = "/search/"