
title = "Cheng Tan's website"
author = "Cheng Tan"
copyright = "2014-{{ YEAR }}"
description = """
Website of Cheng Tan
"""

profilePicture = "images/profile.jpg"
favicon = "favicons/"

keywords = ""

contentratio = 0.7

# example ["css/custom.css"]
customCss = ["css/cnfont.css"]
# example ["js/custom.js"]
customJs = [] 

mainSections = ["post"]

images = ["images/site-feature-image.png"]

doNotLoadAnimations = false

# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"

# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"

# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"

# Read More links for truncated summaries
# readMore = true

# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "mathjax"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/oinil"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/noinil"

[[socialIcons]]
icon = "fas fa-user-graduate"
title = "scholar"
url = "https://scholar.google.co.jp/citations?user=m1aWrJsAAAAJ"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:ctan@c-tan.com"
