# PaperMod Configuration
author = "Cheng Tan"
comments = true

[assets]
    favicon = "favicons/favicon-32x32.png"
    apple_touch_icon = "favicons/apple-touch-icon.png"

description = "Website of Cheng Tan"
keywords = ["Research", "Bioinformatics", "LaTeX"]
images = ["images/site-feature-image.png"]

# Default theme: "light", "dark", "auto"
defaultTheme = "auto"
# disableThemeToggle = false

showToc = true
TocOpen = false
showReadingTime = true
showShareButtons = true
showPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true

[profileMode]
    enabled = true
    title = "Cheng Tan (谭丞)"
    subtitle = "Researcher | Bioinformatics | LaTeX Enthusiast"
    imageUrl = "images/profile.png"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "Cheng Tan"
    [[profileMode.buttons]]
        name = "Blog"
        url = "post"
    [[profileMode.buttons]]
        name = "Publications"
        url = "publication"

[[socialIcons]]
    name = "twitter"
    url = "https://twitter.com/oinil"
[[socialIcons]]
    name = "github"
    url = "https://github.com/noinil"
[[socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.co.jp/citations?user=m1aWrJsAAAAJ"
[[socialIcons]]
    name = "email"
    url = "mailto:ctan@c-tan.com"



# Analytics
# [analytics.google]
#     id = "UA-XXXXX-X"

[markup.goldmark.renderer]
    unsafe = true # For HTML in Markdown

[math]
    enable = true